//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Models;

    public partial class HotelDBEntities : DbContext
    {
 
        public HotelDBEntities()
            //: base("HotelDBEntities")
            : base(GetConnectionString())
        {
           // base.Database.Connection.ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["conString"].ConnectionString;
        }

        public static string GetConnectionString()
        {
            string constr  = System.Configuration.ConfigurationManager.ConnectionStrings["HotelDBEntities"].ConnectionString;
            //如果constr加密，那么解密后返回
            return constr;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
 
        public virtual DbSet<Dishes> Dishes { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public virtual DbSet<DishesBook> DishesBook { get; set; }
        public virtual DbSet<DishesCategory> DishesCategory { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategory { get; set; }
        public virtual DbSet<Recruitment> Recruitment { get; set; }
        public virtual DbSet<Suggestion> Suggestion { get; set; }
        public virtual DbSet<SysAdmins> SysAdmins { get; set; }
    }
}
