//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Dishes
    {
        public int DishesId { get; set; }
        public string DishesName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public virtual DishesCategory DishesCategory { get; set; }

        /// <summary>
        /// 这个字段非EF映射属性，所以使用    [NotMapped]特性，告诉orm框架，该属性不参与映射
        /// </summary>
        [NotMapped]
        public string DishesImg
        {
            get { return DishesName + ".png"; }
        }
    }
}
